spring.application.name=Feed-Service
server.port=8093

livekit.api.key = APIRtS9ErE2GyyD
livekit.api.secret= SjUjs7679z3Em0dtzXe0hvCHCZTe12k0RepFcC4omVNB

aws.region=ap-south-1
aws.s3.bucket-name= media-service

aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}


# multipart upload enable
spring.servlet.multipart.enabled=true

# maximum single file size
spring.servlet.multipart.max-file-size=10MB

# maximum total request size
spring.servlet.multipart.max-request-size=10MB

spring.threads.virtual.enabled=true
