spring.application.name=Dating-app_server

server.port=8761

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Prevent self-registration
eureka.instance.hostname=localhost

# Optional: Disable self-preservation (useful for local development)
eureka.server.enable-self-preservation=false

# Optional: Disable registry sync retries
eureka.server.wait-time-in-ms-when-sync-empty=0
